http:
  port: "8081"
  
anypoint:
  api:
    id: "19278516"

racedata:
  host: race-data-sapi
  port: "8081"
  protocol: HTTP
  path: /api

  
scorekeeper:
  host: beyond-test.anypointspeedway.com
  port: "443"
  protocol: HTTP
  path: /scorekeeper-sapi
  
practice:
  expiry: "7200" # seconds